### ISSUE TITLE
Image bombs if node_modules is missing

### ISSUE THREAD

**Issue by jrock2004** [danlynn/ember-cli#12]
So I have created a `docker-compose` file so I do not need to run the commands. The problem is, if node modules is missing, it does not do the install of them.

```
version: '3'

services:
  ember:
    image: danlynn/ember-cli:2.16.2
    container_name: southcity
    ports:
      - 4200:4200
      - 7020:7020
      - 7357:7357
    volumes:
      - .:/myapp:delegated
      - /myapp/node_modules
      - /myapp/tmp
      - /myapp/dist
```

Thoughts?
