### ISSUE TITLE
Add an environment variable exposing image configuration

### ISSUE THREAD

**Issue by 0x0badc0de** [danlynn/ember-cli#16]
It would be nice to have some environment variable like `EMBER_CLI_IMAGE_VERSION=ember-2.18.0-node-8.9`.
Possible usage - as a cache key in gitlab CI so builds having different ember-cli images use different `node_modules` caches.

**Comment by danlynn** [comment]
Wouldn't it be better if you handled that in your volumization?  This would keep them separate and improve performance because it wouldn't be shared back to the host filesystem.  For example, in your docker-compose, you could do something like:
```
services:
  ember:
    volumes:
      - .:/myapp
      - node_modules:/myapp/node_modules_ember_cli_3.0.0_8.9
```
