### ISSUE TITLE
Docker for ember cli 2.6.2 and node 10.16.2, what's the expected docker-compose.yaml and Dockerfile?

### ISSUE THREAD

**Issue by michaelstokes93** [danlynn/ember-cli#32]
Have an ember app using ember cli 2.6.2 and node 10.16.2. Trying to use docker and have been referencing https://github.com/danlynn/ember-cli/tree/2.6.2.

**Custom Dockerfile required to use a later version of node (10.16.2 rather than 4.2.3)**
- Same as https://github.com/danlynn/ember-cli/blob/2.6.2/Dockerfile other than the node version
- docker compose will not reference image but instead the custom Dockerfile

**Questions**
1. Assumably the only difference to the https://github.com/danlynn/ember-cli/blob/2.6.2/Dockerfile would be the node version?
2. What's the expected docker-compose.yaml? https://github.com/danlynn/ember-cli/tree/2.6.2#how-to-use mentions that the `docker-compose.yml` file should be similar to the following: 

```
ember: &defaults
  image: danlynn/ember-cli:2.6.2 (have to use custom Dockerfile because of greater than node version)
  volumes:
    - .:/myapp

npm:
  <<: *defaults
  entrypoint: ['/usr/local/bin/npm']

bower:
  <<: *defaults
  entrypoint: ['/usr/local/bin/bower', '--allow-root']

server:
  <<: *defaults
  command: server --watcher polling
  ports:
    - "4200:4200"
    - "35729:35729" 
 ```
 
 As far as I'm aware, that's not a valid `docker-compose.yaml` file but I don't know what's expected?
 
 Thanks for your help!
