### ISSUE TITLE
Test Server Error

### ISSUE THREAD

**Issue by evandavey** [danlynn/ember-cli#9]
When trying to run ember test --server I always get an error similar to below, and the build process never completes.  Running test without the server flag works fine.

```
Error: ENOTDIR: not a directory, open '/myapp/tmp/broccoli_persistent_filterbabel__babel_ember_data-input_base_path-O69lbNX1.tmp/ember-data/serializers/json.js'
```

**Comment by danlynn** [comment]
That sort of looks like a project-specific issue.  Can you replicate that on a fresh build of a new ember project (`ember init`)?  I'm still without power due to the hurricane.  So, if you find that it is something that applies generally to all projects using the image, let me know.  Also, let me know if you find a solution. :-)

**Comment by evandavey** [comment]
To add a bit more colour, I'm using Docker for Windows with a shared mount.  If I locally install ember-cli (within Windows Ubuntu) and run ember test --server then this works - so it seems to be something to do with the mounted volume and/or docker image.

And I get the same error on a fresh build.  Here's my docker-compose.yml file

```yaml
version: "3"
services:
  app:
    image: danlynn/ember-cli:2.15.1
    volumes:
      - .:/myapp
    command: ['ember','server','--watcher','polling']
```
